---
title: "Plotting Maps Week_6a"
author: "Lipi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
```

# Read in your Data
```{r}
# Read in data on population in California by county
popdata<- read_csv(here("Week_07","Data","CApopdata.csv"))

#read in data on number of seastars at different field sites
stars<- read_csv(here("Week_07","Data","stars.csv"))

# get data for the entire world
world<-map_data("world")
head(world)

# get data for the USA
usa<-map_data("usa")
head(usa)

# get data for italy
italy<-map_data("italy")
head(italy)

# get data for states
states<-map_data("state")
head(states)

# get data for counties
counties<-map_data("county")
head(counties)
```

# Make a map of the world
```{r}
ggplot()+
  geom_polygon(data = world, aes(x = long, y = lat, group = group))

## What happens if I forget group = group?

ggplot()+
  geom_polygon(data = world, aes(x = long, y = lat))


ggplot()+
    geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group, 
                   fill = region),
               color = "black")+ ## Add color to the lines and fill.
  guides(fill = FALSE)+
  theme_minimal()+ ## adds a theme
  theme(panel.background = element_rect(fill = "lightblue"))+ ## Make the ocean blue.
  coord_map(projection = "mercator",
            xlim = c(-180,180)) ## Use a mercator projection

```

# Let's make a map of just California
```{r}
# Use the states dataset
head(states)

# Use the states dataset
CA_data<-states %>%
  filter(region == "california")

ggplot()+
geom_polygon(data = CA_data, 
             aes(x = long, 
                 y = lat, 
                 group = group), 
             color = "black")+
  coord_map()+
  theme_void() ## Gets rid of everything

```

# Plot the population of every county in California.
```{r}
# First, we need to get the county level data and join it with our dataset on population (How do I do it?)
# Look at the county data
head(counties)[1:3,] # only showing the first 3 rows for space

CApop_county<-popdata %>%
  select("subregion" = County, Population)  %>% # rename the county col
  inner_join(counties) %>%
  filter(region == "california") # some counties have same names in other states
head(CApop_county)


ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),
             color = "black")+
  geom_point(data = stars, # add a point at all my sites
             aes(x = long,
                 y = lat,
                 size = star_no))+
  
  coord_map()+ # automatically puts in mercator projection, only for US
  theme_void()+
  scale_fill_gradient(trans = "log10")+ # using log will give gradient of colors 
  labs(size = "# stars/m2")
head(stars)


```

