---
title: "Working with Google Maps"
author: "Lipi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load the libraries
```{r}
library(ggmap)
library(tidyverse)
library(here)
library(ggsn)

register_google(key = "AIzaSyApwNnOfl8RbwOcx6NXsKEmFHhr-AgJiho", write = TRUE)
```

# Load the data
```{r}
ChemData<-read_csv(here("Week_07","Data","chemicaldata_maunalua.csv"))

glimpse(ChemData)

```

# Get basic map of Oahu.
```{r}
Oahu<-get_map("Oahu")

# Use ggmap to plot the base layer
ggmap(Oahu)
```

# Get coordinates for Wailupe on Oahu.
```{r}
Oahu<-get_map("Oahu")

# Use ggmap to plot the base layer
ggmap(Oahu)

#Make a data frame of lon and lat coordinates
WP<-data.frame(lon = -157.7621, lat = 21.27427) # coordinates for Wailupe

# Get base layer
Map1<-get_map(WP)

# plot it
ggmap(Map1)

# Zoom in on a location (3: continent level ---to--- 20: zooooomed in)
Map1<-get_map(WP,zoom = 17)
ggmap(Map1)

# Change the map type
Map1<-get_map(WP,zoom = 17, maptype = "watercolor")
ggmap(Map1)

Map1<-get_map(WP,zoom = 17, maptype = "satellite")
ggmap(Map1)+
  geom_point(data = ChemData,
             aes(x = Long, y = Lat, color = Salinity),
             size = 4) +
  scale_color_viridis_c()+
  scalebar( x.min = -157.766, x.max = -157.758,
           y.min = 21.2715, y.max = 21.2785,
            dist = 250, dist_unit = "m", model = "WGS84", 
            transform = TRUE, st.color = "white",
            box.fill = c("yellow", "white"))

# Don't know the exact lat and long?
# Use geocode() to get exact locations that you can then use in the maps.

geocode("the white house")

geocode("California State University, Northridge")
```

