---
title: "Homework for Week_6a"
author: "Lipi"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load the libraries
```{r}
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
library(tidyr)
library(dplyr)
```

# Read in your Data
```{r}
meteorites <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-11/meteorites.csv")
View(meteorites)

# get data for the entire world
world<-map_data("world")
head(world)

# get data for USA
usa<-map_data("usa")
head(usa)

# get data for italy
italy<-map_data("italy")
head(italy)

# get data for states
states<-map_data("state")
head(states)

# get data for counties
counties<-map_data("county")
head(counties)

```

# Make a map of the world
```{r}
ggplot()+
    geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group, 
                   fill = region),
               color = "black")+ ## Add color to the lines and fill.
  guides(fill = FALSE)+
  theme_minimal()+ ## adds a theme
  theme(panel.background = element_rect(fill = "lightblue")) ## Make the ocean blue.
```

# Make a plot of just california
```{r}
# Use the states dataset
head(states)

# Use the states dataset
CA_data<-states %>%
  filter(region == "california")

ggplot()+
geom_polygon(data = CA_data, 
             aes(x = long, 
                 y = lat, 
                 group = group), 
             color = "black")+
  coord_map()
```

# Filter out meteorites fallen in the year 1950 only.
```{r}
new_met_data<-filter(.data = meteorites, year == "1950")
View(new_met_data)
```

# Pivot data longer
```{r}
pivoted_met_data<-new_met_data %>%
  pivot_longer(cols = "class", "fall", # the cols you want to pivot/select
              names_to = "Variables", # the names of the new cols with all the column names
              values_to = "Values") # names of the new column with all the values
View(pivoted_met_data)
```

# Plot the meteorites data in California in 1950. 
```{r}
# First, we need to get the county level data and join it with our dataset on population (How do I do it?)
# Look at the county data
head(counties)[1:5,] # only showing the first 3 rows for space

CA_met_data<-new_met_data %>%
  select("class" = county, mass) %>% # rename the county col
  inner_join(counties) %>%
  filter(region == "california") # some counties have same names in other states
head(CA_met_data)
```

